<?php 
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Wooflow_Email_Option {

	/**
	 * Get the class instance
	 *
	 * @since  1.0
	 * @return Wooflow_Email_Option
	*/

	public $defaults;
	
	public static function get_instance() {

		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Instance of this class.
	 *
	 * @var object Class Instance
	*/
	private static $instance;

	/**
	 * Initialize the main plugin function
	 * 
	 * @since  1.0
	*/
	public function __construct() {

		// Get our Customizer defaults
		$this->defaults = $this->wooflow_generate_defaults();			
	}

	/**
	 * Code for initialize default value for customizer
	*/	
	public function wooflow_generate_defaults() {
		$mydate=getdate(gmdate('U'));
		$customizer_defaults = array(
			'email_selected_order_id' 						=> 'mockup',
			'wooflow_email_template' 						=> 'trackship_SaaS',
			'secondary_color' 								=> '#180a0a',
			'all_link_color' 								=> '#114ed6',
			'all_border_color' 								=> '#e0e0e0',
			'footer_text_color' 							=> '#212121',
			'subscription_order_summary_background_color' 	=> '#ffffff',
			'subscription_table_padding' 					=> 0,
			'subscription_table_left_right_padding' 		=> 0,
			'subscription_order_details_border' 			=> 1,
			'subscription_order_details_border_radius' 		=> 1,
			'heading_font_size' 							=> 18,
			'contant_font_size' 							=> 15,
			'fluid_button_size' 							=> 15,
			'fluid_button_background_color' 				=> '#3858e9',
			'fluid_button_font_color' 						=> '#ffffff',
			'fluid_button_radius' 							=> 5,
			'fluid_button_border' 							=> 1,
			'container_background_color' 					=> '#f5f5f5',
			'container_padding_top' 						=> 20,
			'container_padding_bottom' 						=> 20,
			'container_width' 								=> 600,
			'container_padding_left_right' 					=> 20,
			'container_border' 								=> 1,
			'container_border_radius' 						=> 20,
			'logo_width' 									=> 200,
			'header_width' 									=> 1,
			'logo_position' 								=> 'inside',
			'body_background_color'							=> '#f5f5f5',
			'heading_text_alignment'						=> 'left',
			'logo_alignment' 								=> 'left',
			'header_bg_color' 								=> '#fff',
			'header_font_color' 							=> '#212121',
			'header_font_size' 								=> 20,
			'heading_padding_top' 							=> 20,
			'heading_padding_bottom' 						=> 20,
			'heading_padding_left_right' 					=> 30,
			'show_product_image' 							=> '0',
			'order_summary_background_color' 				=> '#ffffff',
			'table_padding' 								=> 10,
			'table_left_right_padding' 						=> 0,
			'order_details_border' 							=> 1,
			'order_details_border_radius' 					=> 0,
			'address_alignment' 							=> 'left',
			'address_box_background_color' 					=> '#ffffff',
			'address_border' 								=> 1,
			'address_border_radius' 						=> 1,
			'email_footer_text' 							=> 'Copyright © ' . $mydate['year'] . ' TrackShip, All rights reserved.',
			'footer_layout' 								=> 'center',
			'footer_position' 								=> 'Inside',
			'footer_width' 									=> 1,
			'footer_background_color' 						=> '#fff',
			'footer_icon_background_color' 					=> '#ffffff',
			'footer_border_bottom' 							=> 'solid',
			'footer_border_bottom_color' 					=> '#dcdee2',
			'footer_border_bottom_width' 					=> 1,
			'link_show' 									=> 1,
			'footer_text_add' 								=> 'Link 1',
			'facebook_link' 								=> 'https://www.facebook.com/trackshipcom/',
			'twitter_link' 									=> 'https://twitter.com/trackship',
			'linkedin_link' 								=> 'https://www.linkedin.com/company/trackship/',
			'instagram_link' 								=> 'https://www.instagram.com/',
			'custom_style_textarea' 						=> '',
			'table_heading_color'							=> '#212121',
			'table_heading_font_family'						=> '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif',
			'table_heading_font_size'						=> 15,
			'table_heading_font_style'						=> 600,
			'table_heading_line_height'						=> 35,
			'table_content_font_family'						=> '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif',
			'table_content_font_size'						=> 15,
			'variation_product_font_size'					=> 13,
			'table_content_font_style'						=> 400,
			'table_content_line_height'						=> 25,
			'address_table_font_family'						=> '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif',
			'address_table_font_size'						=> 15,
			'address_table_font_style'						=> 400,
			'address_table_line_height'						=> 25,
			'footer_content_font_family'					=> '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif',
			'footer_content_font_size'						=> 15,
			'footer_content_font_style'						=> 400,
			'footer_content_line_height'					=> 20,
			'table_padding_top'								=> 15,
			'table_padding_bottom'							=> 0,
			'header_font_family'							=> '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif',
			'header_font_style'								=> 600,
			'header_line_height'							=> 20,
			'subscription_table_padding_top'				=> 10,
			'subscription_table_padding_bottom'				=> 0,
			'address_table_padding_top'						=> 0,
			'address_table_padding_bottom'					=> 0,
			'address_order_details_border'					=> 1,
		);

		return apply_filters( 'wooflow_customizer_defaults', $customizer_defaults );
	}

	//customizer options array
	public function email_customize_setting_options_func() {
	
		$email_type = isset( $_GET['email_type'] ) ? sanitize_text_field($_GET['email_type']) : get_option( 'orderStatus', 'new_order' );
		$order_id = get_option( 'email_selected_order_id', $this->defaults['email_selected_order_id'] );
		$header_image_option = get_option('woocommerce_email_header_image');
		$email_customizer_settings = get_option('email_customizer_settings_option', array());
		$wec = Wooflow_Email_Customizer()->default_content_customizer;
		$footer_position = $wec->get_customizer_option_value_from_array('email_customizer_settings_option', 'footer_position', $this->defaults['footer_position'] );
		$email_template = $wec->get_customizer_option_value_from_array('email_customizer_settings_option', 'wooflow_email_template', $this->defaults['wooflow_email_template'] );
		$email_iframe_url = $wec->get_email_preview_url( $email_type );
		
		$settings = array(			
			//panels
			'email_content'	=> array(
				'id'	=> 'email_content',
				'class' => 'zoremmail-panel-title options_panel',
				'title'	=> esc_html__( 'Email Content', 'wooflow-email-customizer' ),
				'type'	=> 'panel',
				'iframe_url' => $email_iframe_url,
				'show'	=> true,
			),
			'select_email_template' => array(
				'id'     => 'select_email_template',
				'class' => 'zoremmail-panel-title options_panel',
				'title'       => esc_html__( 'Email Template', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
			),
			'header1' => array(
				'id'     => 'select_email_template',
				'title'       => esc_html__( 'Email Template', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'select_email_template',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'email_templets' => array(
				'id'	=> 'email_templets',
				'type'	=> 'sub-panel',
				'parent'=> 'select_email_template',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'heading1' => array(
				'id'     => 'email_templets',
				'title'       => esc_html__( 'Email Template', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'email_templets',
				'show'     => true,	
			),
			'wooflow_email_template' => array(
				'title'    => esc_html__( 'Select Template', 'wooflow-email-customizer' ),
				'type'     => 'select_template',
				'default'  => isset($email_customizer_settings['wooflow_email_template']) ? $email_customizer_settings['wooflow_email_template'] : $this->defaults['wooflow_email_template'],
				'show'     => true,
				'options'  => array(
					'woocommerce' => __( 'Woocommerce', 'wooflow-email-customizer' ),
					'trackship_SaaS' => __( 'Trackship SaaS', 'wooflow-email-customizer' ),
				),
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class' => 'border_bottom_none',
			),
			'email_design'	=> array(
				'id'	=> 'email_design',
				'class' => 'zoremmail-panel-title options_panel',
				'title'	=> esc_html__( 'Email Style', 'wooflow-email-customizer' ),
				'type'	=> 'panel',
				'iframe_url' => $email_iframe_url,
				'show'	=> true,
			),

			//sub-panels-heading
			'header' => array(
				'id'     => 'email_content',
				'title'       => esc_html__( 'Email Content', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'email_content',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'email_settings_two' => array(
				'id'	=> 'email_settings_two',
				'title'       => esc_html__( 'Customer Email', 'wooflow-email-customizer' ),
				'type'	=> 'sub-panel',
				'parent'=> 'email_content',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			
			// //three second panel
			// 'email_settings_three' => array(
			// 	'id'	=> 'email_settings_three',
			// 	'title'       => esc_html__( 'Admin Email', 'wooflow-email-customizer' ),
			// 	'type'	=> 'sub-panel',
			// 	'parent'=> 'email_content',
			// 	'show'	=> true,
			// 	'class' => 'sub_options_panel',
			// ),
			
			// //five second panel
			// 'email_settings_five' => array(
			// 	'id'	=> 'email_settings_five',
			// 	'title'       => esc_html__( 'Subscription Email', 'wooflow-email-customizer' ),
			// 	'type'	=> 'sub-panel',
			// 	'parent'=> 'email_content',
			// 	'show'  => Wooflow_Email_Customizer()->is_subscription_active() ? true : false,
			// 	'class' => 'sub_options_panel',
			// ),
			'header2' => array(
				'id'     => 'email_design',
				'title'       => esc_html__( 'Email Style', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'email_design',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'color_panel' => array(
				'id'     => 'color_panel',
				'title'       => esc_html__( 'Color', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel',
				'parent'	=> 'email_design',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'Typography_panel' => array(
				'id'     => 'Typography_panel',
				'title'       => esc_html__( 'Typography', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel',
				'parent'	=> 'email_design',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'Button_panel' => array(
				'id'     => 'Button_panel',
				'title'       => esc_html__( 'Buttons', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel',
				'parent'	=> 'email_design',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'Container_panel' => array(
				'id'     => 'Container_panel',
				'class' => 'zoremmail-panel-title options_panel',
				'title'       => esc_html__( 'Email Container', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
			),
			'header_panel' => array(
				'id'     => 'header_panel',
				'class' => 'zoremmail-panel-title options_panel',
				'title'       => esc_html__( 'Email Header', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
			),
			'woocommerce_panel' => array(
				'id'     => 'woocommerce_panel',
				'class' => 'zoremmail-panel-title options_panel',
				'title'       => esc_html__( 'Woocommerce', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
			),
	
			//sub-second-panel-end
			'email_footer' => array(
				'id'     => 'email_footer',
				'class' => 'zoremmail-panel-title options_panel',
				'title'       => esc_html__( 'Email Footer', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
			),
			'custom_style' => array(
				'id'     => 'custom_style',
				'title'       => esc_html__( 'Custom CSS', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel',
				'parent'	=> 'email_design',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'import_export_btn' => array(
				'id'     => 'import_export_btn',
				'class' => 'zoremmail-panel-title options_panel',
				'title'       => esc_html__( 'Import Export', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'send_test_email' => array(
				'id'     => 'send_test_email',
				'title'       => esc_html__( 'Send Test Email', 'wooflow-email-customizer' ),
				'type'     => 'panel',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			
			//sub_panels
			'header3' => array(
				'id'     => 'woocommerce_panel',
				'title'       => esc_html__( 'Woocommerce', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'woocommerce_panel',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			//color section
			'heading6' => array(
				'id'     => 'color_panel',
				'title'       => esc_html__( 'Color', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'color_panel',
				'show'     => true,	
			),
			'header_font_color' => array(
				'title'    => esc_html__( 'Header Font Color', 'wooflow-email-customizer' ),
				'parent'	=> 'email_heading',
				'default'  => isset($email_customizer_settings['header_font_color']) ? $email_customizer_settings['header_font_color'] : $this->defaults['header_font_color'],
				'type'     => 'color',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'selectors'     => array(
					'td#header_wrapper h1, .heading_with_content h1'   => array( 'color' ),
				),
			),
			'table_heading_color' => array(
				'title'    => esc_html__( 'Table Heading Color', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['table_heading_color']) ? stripslashes($email_customizer_settings['table_heading_color']) : $this->defaults['table_heading_color'],
				'type'     => 'color',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'selectors'   => array(
					'.woo_product_th, .woo_price_th, .subscription_id_th, #addresses h2, h2'   => array( 'color' ),
				),
			),			
			'woocommerce_email_text_color' => array(
				'title'    => esc_html__( 'Content Color', 'wooflow-email-customizer' ),
				'default'  => get_option( 'woocommerce_email_text_color' ),
				'type'     => 'color',
				'show'     => true,
				'option_name'=> 'woocommerce_email_text_color',
				'option_type'=> 'key',
				'class'     => 'colorset',
				'style'  	=> 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array(
					'.woocommerce_table_style tr td span, .woocommerce_table_style tr.woo_label_tr th, .subscription-table tr.woo_label_tr th, .subscription-table tr.woo_label_tr td, table#addresses .address p, p.first_span_text, p.additional_content_h6, .subscription-table th.subscription_price_th, .subscription-table td.subscription_price, table.subscription-table td.subscription_end_date, table.subscription-table th.subscription_end_date_th, .last_message, .additional_content_h6, p, ul li' => array( 'color' ) )
					: array( '#body_content_inner .woocommerce_table_style *, #body_content_inner .subscription-table tr th, #body_content_inner .subscription-table tr td, .first_span_text, .address p, .last_message, .additional_content_h6, p, ul li' => array( 'color' ),
				),
			),
			'all_link_color' => array(
				'title'    => esc_html__( 'Link Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'parent'	=> 'email_colors',
				'default'  => isset($email_customizer_settings['all_link_color']) ? $email_customizer_settings['all_link_color'] : $this->defaults['all_link_color'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset simple_class',
				'style'   => 'css',
				'selectors'     => array(
					'#body_content_inner > h2 > a, a'     => array( 'color' ),
				),
			),
			'all_border_color' => array(
				'title'    => esc_html__( 'Border Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'parent'	=> 'email_colors',
				'default'  => isset($email_customizer_settings['all_border_color']) ? $email_customizer_settings['all_border_color'] : $this->defaults['all_border_color'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset simple_class',
				'style'   => 'css',
				'selectors'     => array(
					'#template_container, table.woocommerce_table_style,address.address, table.subscription-table, table.addresses, div.heading_with_content, th.subscription_id_th, th.woo_product_th, th.woo_price_th, address.address'	=> array( 'border-color' ),
					'table.subscription-table tr th.subscription_id_th, table.subscription-table tr th.subscription_price_th, table.subscription-table tr th.subscription_start_date_th, table.subscription-table td.subscription_id, table.subscription-table td.subscription_price, table.subscription-table td.subscription_start_date'	=> array( 'border-right-color' ),
					'table.subscription-table td.subscription_id, table.subscription-table td.subscription_price, table.subscription-table td.subscription_start_date, table.subscription-table td.subscription_end_date'	=> array( 'border-top-color' ),
	
					'table.woocommerce_table_style td.woo_image_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style td.woo_price_id, table.woocommerce_table_style th.woo_label_th, td.woo_value_th, th.woo_note_th, td.woo_note_value_th' => array( 'border-top-color' ),
					'table.woocommerce_table_style th.woo_product_th, table.woocommerce_table_style th.woo_qty_th, table.woocommerce_table_style td.woo_image_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style th.woo_label_th, th.woo_note_th' => array( 'border-right-color' ),
				),
			),
			'footer_text_color' => array(
				'title'    => esc_html__( 'Footer Text Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'parent'	=> 'email_colors',
				'default'  => isset($email_customizer_settings['footer_text_color']) ? $email_customizer_settings['footer_text_color'] : $this->defaults['footer_text_color'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset simple_class',
				'style'   => 'css',
				'selectors'     => array(
					'table#template_footer p'     => array( 'color' ),
				),
			),
			'woocommerce_email_background_color' => array(
				'title'    => esc_html__( 'Body Background Color', 'wooflow-email-customizer' ),
				'default'  => get_option( 'woocommerce_email_background_color' ),
				'type'     => 'color',
				'show'     => true,
				'option_name'=> 'woocommerce_email_background_color',
				'option_type'=> 'key',
				'class'     => 'colorset border_bottom_none',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('body'   => array( 'background-color' ) )
					: array('body'   => array( 'background-color' ) ,
				),
			),
			'template_setting_second' => array(
				'id'	=> 'template_setting_second',
				'title'       => esc_html__( 'Order Details', 'wooflow-email-customizer' ),
				'type'	=> 'sub-panel',
				'parent'=> 'woocommerce_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			// 'template_setting_therd' => array(
			// 	'id'	=> 'template_setting_therd',
			// 	'title'       => esc_html__( 'Address', 'wooflow-email-customizer' ),
			// 	'type'	=> 'sub-panel',
			// 	'parent'=> 'woocommerce_panel',
			// 	'show'	=> true,
			// 	'class' => 'sub_options_panel',
			// ),
			'template_setting_four' => array(
				'id'	=> 'template_setting_four',
				'title'       => esc_html__( 'Subscriptions', 'wooflow-email-customizer' ),
				'type'	=> 'sub-panel',
				'parent'=> 'woocommerce_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'subscriptions_table_panel' => array(
				'id'	=> 'subscriptions_table_panel',
				'title'       => esc_html__( 'Subscriptions', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'template_setting_four',
				'show'     => true,	
				'class' => 'sub_second_options_panel',
			),
			'subscription_order_summary_background_color' => array(
				'title'    => esc_html__( 'Order Table Background Color', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['subscription_order_summary_background_color']) ? stripslashes($email_customizer_settings['subscription_order_summary_background_color']) : $this->defaults['subscription_order_summary_background_color'],
				'type'     => 'color',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'default_color' => '#ffffff',
				'class'     => 'colorset subscription_order_summary_background_color',
				'style'  => 'css',
				'selectors'     => array(
					'div.subscription-table-background-color, table.subscription-table'   => array( 'background-color' ),
				),
			),
			'subscription_table_padding_top' => array(
				'title'    => esc_html__( 'Padding Top', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['subscription_table_padding_top']) ? stripslashes($email_customizer_settings['subscription_table_padding_top']) : $this->defaults['subscription_table_padding_top'],
				'type'     => 'range',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 25,
				'unit'	=> 'px',
				'class'		=> 'subscription_table_padding_top',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('table.subscription-table'   => array( 'padding-top' ) )
					: array('div.subscription-table-background-color'   => array( 'margin-top' ) ,
				),
			),
			'subscription_table_padding_bottom' => array(
				'title'    => esc_html__( 'Padding Bottom', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['subscription_table_padding_bottom']) ? stripslashes($email_customizer_settings['subscription_table_padding_bottom']) : $this->defaults['subscription_table_padding_bottom'],
				'type'     => 'range',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 25,
				'unit'	=> 'px',
				'class'		=> 'subscription_table_padding_bottom',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('table.subscription-table'   => array( 'padding-bottom' ) )
					: array('div.subscription-table-background-color'   => array( 'margin-bottom' ) ,
				),
			),
			// 'subscription_table_left_right_padding' => array(
			// 	'title'    => esc_html__( 'Left / Right Padding', 'wooflow-email-customizer' ),
			// 	'default'  => isset($email_customizer_settings['subscription_table_left_right_padding']) ? stripslashes($email_customizer_settings['subscription_table_left_right_padding']) : $this->defaults['subscription_table_left_right_padding'],
			// 	'type'     => 'range',
			// 	'show'     => true,
			// 	'option_name'=> 'email_customizer_settings_option',
			// 	'option_type'=> 'array',
			// 	'min'		=> 0,
			// 	'max'		=> 15,
			// 	'unit'	=> 'px',
			// 	'class'		=> Wooflow_Email_Customizer()->is_subscription_active() ? 'subscription_table_left_right_padding' : ' subscription_table_left_right_padding border_bottom_none ',
			// 	'style'  => 'css',
			// 	'selectors'     => array(
			// 		'table.subscription-table' => array( 'padding-left','padding-right' ),
			// 	),
			// ),
			'subscription_order_details_border' => array(
				'title'    => esc_html__( 'Border Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['subscription_order_details_border']) ? stripslashes($email_customizer_settings['subscription_order_details_border']) : $this->defaults['subscription_order_details_border'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 1,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'subscription_order_details_border',
				'style'  => 'css',
				'selectors'     => array(
					'table.subscription-table, th.subscription_id_th' => array( 'border-width' ),
					'table.subscription-table td.subscription_id, table.subscription-table td.subscription_price, table.subscription-table td.subscription_start_date, table.subscription-table td.subscription_end_date' => array( 'border-top-width' ),
					'table.subscription-table tr th.subscription_id_th, table.subscription-table tr th.subscription_price_th, table.subscription-table tr th.subscription_start_date_th, table.subscription-table td.subscription_id, table.subscription-table td.subscription_price, table.subscription-table td.subscription_start_date' => array( 'border-right-width' ),
					
				),
			),
			'subscription_order_details_border_radius' => array(
				'title'    => esc_html__( 'Border Radius', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['subscription_order_details_border_radius']) ? stripslashes($email_customizer_settings['subscription_order_details_border_radius']) : $this->defaults['subscription_order_details_border_radius'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'subscription_order_details_border_radius border_bottom_none zorem_template_none',
				'style'  => 'css',
				'selectors'     => array(
					'table.subscription-table' => array( 'border-radius' ),
				),
			),
			'template_setting_five' => array(
				'id'	=> 'template_setting_five',
				'title'       => esc_html__( 'Addresses', 'wooflow-email-customizer' ),
				'type'	=> 'sub-panel',
				'parent'=> 'woocommerce_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'address_table_panel' => array(
				'id'	=> 'address_table_panel',
				'title'       => esc_html__( 'Addresses', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'template_setting_five',
				'show'     => true,	
				'class' => 'sub_second_options_panel',
			),
			'address_table_padding_top' => array(
				'title'    => esc_html__( 'Padding Top', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['address_table_padding_top']) ? stripslashes($email_customizer_settings['address_table_padding_top']) : $this->defaults['address_table_padding_top'],
				'type'     => 'range',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 25,
				'unit'	=> 'px',
				'class'		=> 'address_table_padding_top',
				'style'  => 'css',
				'selectors'     => array(
					'table#addresses' => array( 'padding-top' ),
				),
			),
			'address_table_padding_bottom' => array(
				'title'    => esc_html__( 'Padding Bottom', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['address_table_padding_bottom']) ? stripslashes($email_customizer_settings['address_table_padding_bottom']) : $this->defaults['address_table_padding_bottom'],
				'type'     => 'range',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 25,
				'unit'	=> 'px',
				'class'		=> 'address_table_padding_bottom',
				'style'  => 'css',
				'selectors'     => array(
					'table#addresses' => array( 'padding-bottom' ),
				),
			),
			'address_order_details_border' => array(
				'title'    => esc_html__( 'Border Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['address_order_details_border']) ? stripslashes($email_customizer_settings['address_order_details_border']) : $this->defaults['address_order_details_border'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 1,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'address_order_details_border',
				'style'  => 'css',
				'selectors'     => array(
					'table#addresses address.address' => array( 'border-width' ),
				),
			),
			'Typography_second_panel' => array(
				'id'	=> 'Typography_second_panel',
				'title'       => esc_html__( 'Typography', 'wooflow-email-customizer' ),
				'type'	=> 'section',
				'parent'=> 'Typography_panel',
				'show'	=> true,
				'class' => 'sub_second_options_panel',
			),
			'email_style_typography_header sub_menu_style' => array(
				'title'    => esc_html__( 'EMAIL HEADER', 'wooflow-email-customizer' ),
				'class'     => 'header_style_set',
			),
			'header_font_family' => array(
				'title'    => esc_html__( 'Font Family', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['header_font_family']) ? stripslashes($email_customizer_settings['header_font_family']) : $this->defaults['header_font_family'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'options'  => array(
					'"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif' => __( '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif', 'wooflow-email-customizer' ),
					'Arial, Helvetica, sans-serif' => __( 'Arial, Helvetica, sans-serif', 'wooflow-email-customizer' ),
					'"Arial Black", Gadget, sans-serif' => __( '"Arial Black", Gadget, sans-serif', 'wooflow-email-customizer' ),
					'"Courier New", Courier, monospace' => __( '"Courier New", Courier, monospace', 'wooflow-email-customizer' ),
					'Impact, Charcoal, sans-serif' => __( 'Impact, Charcoal, sans-serif', 'wooflow-email-customizer' ),
					'"Lucida Sans Unicode", "Lucida Grande", sans-serif' => __( '"Lucida Sans Unicode", "Lucida Grande", sans-serif', 'wooflow-email-customizer' ),
					'"Palatino Linotype", "Book Antiqua", Palatino, serif' => __( '"Palatino Linotype", "Book Antiqua", Palatino, serif', 'wooflow-email-customizer' ),
					'Georgia, serif' => __( 'Georgia, serif', 'wooflow-email-customizer' ),
				),
				'selectors'     => array(
					'h1' => array( 'font-family' ),
				),
			),
			'header_font_size' => array(
				'title'    => esc_html__( 'Header Font Size', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'parent'	=> 'email_heading',
				'default'  => isset($email_customizer_settings['header_font_size']) ? $email_customizer_settings['header_font_size'] : $this->defaults['header_font_size'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 10,
				'max'		=> 35,
				'unit'	=> 'px',
				'show'     => true,
				'style'  => 'css',
				'selectors'     => array(
					'#header_wrapper h1, .heading_with_content h1' => array( 'font-size' ),
				),
			),
			'header_font_style' => array(
				'title'    => esc_html__( 'Font Style', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['header_font_style']) ? $email_customizer_settings['header_font_style'] : $this->defaults['header_font_style'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'100' => __( '100', 'wooflow-email-customizer' ),
					'200' => __( '200', 'wooflow-email-customizer' ),
					'300' => __( '300', 'wooflow-email-customizer' ),
					'400' => __( '400', 'wooflow-email-customizer' ),
					'500' => __( '500', 'wooflow-email-customizer' ),
					'600' => __( '600', 'wooflow-email-customizer' ),
					'700' => __( '700', 'wooflow-email-customizer' ),
					'bold' => __( 'Bold', 'wooflow-email-customizer' ),
				),
				'style'   => 'css',
				'selectors'     => array(
					'h1' => array( 'font-weight' ),
				),
			),
			'header_line_height' => array(
				'title'    => esc_html__( 'Content Line Height', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['header_line_height']) ? $email_customizer_settings['header_line_height'] : $this->defaults['header_line_height'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'min'       => 20,
				'max'       => 35,
				'unit'      => 'px',
				'class'     => 'header_line_height',
				'style'   => 'css',
				'selectors'     => array(
					'h1, .user_id'   => array( 'line-height' ),
				),
			),
			'email_style_typography_table_heading sub_menu_style' => array(
				'title'    => esc_html__( 'CONTENT HEADER', 'wooflow-email-customizer' ),
				'class'     => 'header_style_set',
			),
			'table_heading_font_family' => array(
				'title'    => esc_html__( 'Font Family', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['table_heading_font_family']) ? stripslashes($email_customizer_settings['table_heading_font_family']) : $this->defaults['table_heading_font_family'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'options'  => array(
					'"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif' => __( '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif', 'wooflow-email-customizer' ),
					'Arial, Helvetica, sans-serif' => __( 'Arial, Helvetica, sans-serif', 'wooflow-email-customizer' ),
					'"Arial Black", Gadget, sans-serif' => __( '"Arial Black", Gadget, sans-serif', 'wooflow-email-customizer' ),
					'"Courier New", Courier, monospace' => __( '"Courier New", Courier, monospace', 'wooflow-email-customizer' ),
					'Impact, Charcoal, sans-serif' => __( 'Impact, Charcoal, sans-serif', 'wooflow-email-customizer' ),
					'"Lucida Sans Unicode", "Lucida Grande", sans-serif' => __( '"Lucida Sans Unicode", "Lucida Grande", sans-serif', 'wooflow-email-customizer' ),
					'"Palatino Linotype", "Book Antiqua", Palatino, serif' => __( '"Palatino Linotype", "Book Antiqua", Palatino, serif', 'wooflow-email-customizer' ),
					'Georgia, serif' => __( 'Georgia, serif', 'wooflow-email-customizer' ),
				),
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woo_product_th, .woo_product_th a, .woo_price_th, .subscription_id_th, .subscription_id_th a, #addresses h2, h2'   => array( 'font-family' ) )
					: array('h2'   => array( 'font-family' ) ,
				),
			),
			'table_heading_font_size' => array(
				'title'    => esc_html__( 'Header Font Size', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['table_heading_font_size']) ? $email_customizer_settings['table_heading_font_size'] : $this->defaults['table_heading_font_size'],
				'show'     => true,
				'class'     => 'colorset simple_class',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 10,
				'max'		=> 20,
				'unit'	=> 'px',
				'class'		=> 'table_heading_font_size',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woo_product_th, .woo_product_th a, .woo_price_th, .subscription_id_th, .subscription_id_th a, #addresses h2, h2'   => array( 'font-size' ) )
					: array('#body_content_inner h2'   => array( 'font-size' ) ,
				),
			),
			'table_heading_font_style' => array(
				'title'    => esc_html__( 'Font Style', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['table_heading_font_style']) ? $email_customizer_settings['table_heading_font_style'] : $this->defaults['table_heading_font_style'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'100' => __( '100', 'wooflow-email-customizer' ),
					'200' => __( '200', 'wooflow-email-customizer' ),
					'300' => __( '300', 'wooflow-email-customizer' ),
					'400' => __( '400', 'wooflow-email-customizer' ),
					'500' => __( '500', 'wooflow-email-customizer' ),
					'600' => __( '600', 'wooflow-email-customizer' ),
					'700' => __( '700', 'wooflow-email-customizer' ),
					'bold' => __( 'Bold', 'wooflow-email-customizer' ),
				),
				'style'   => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woo_product_th, .woo_product_th a, .woo_price_th, .subscription_id_th, .subscription_id_th a, #addresses h2, h2'   => array( 'font-weight' ) )
					: array('h2'   => array( 'font-weight' ) ,
				),
			),
			'table_heading_line_height' => array(
				'title'    => esc_html__( 'Content Line Height', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['table_heading_line_height']) ? $email_customizer_settings['table_heading_line_height'] : $this->defaults['table_heading_line_height'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'min'       => 10,
				'max'       => 50,
				'unit'      => 'px',
				'class'     => 'table_heading_line_height',
				'style'   => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woo_product_th, .woo_product_th a, .woo_price_th, .subscription_id_th, .subscription_id_th a, #addresses h2, h2'   => array( 'line-height' ) )
					: array('h2'   => array( 'line-height' ) ,
				),
			),
			'email_style_typography_email_content sub_menu_style' => array(
				'title'    => esc_html__( 'TABLE CONTENT', 'wooflow-email-customizer' ),
				'class'     => 'header_style_set',
			),
			'table_content_font_family' => array(
				'title'    => esc_html__( 'Font Family', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['table_content_font_family']) ? stripslashes($email_customizer_settings['table_content_font_family']) : $this->defaults['table_content_font_family'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'options'  => array(
					'"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif' => __( '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif', 'wooflow-email-customizer' ),
					'Arial, Helvetica, sans-serif' => __( 'Arial, Helvetica, sans-serif', 'wooflow-email-customizer' ),
					'"Arial Black", Gadget, sans-serif' => __( '"Arial Black", Gadget, sans-serif', 'wooflow-email-customizer' ),
					'"Courier New", Courier, monospace' => __( '"Courier New", Courier, monospace', 'wooflow-email-customizer' ),
					'Impact, Charcoal, sans-serif' => __( 'Impact, Charcoal, sans-serif', 'wooflow-email-customizer' ),
					'"Lucida Sans Unicode", "Lucida Grande", sans-serif' => __( '"Lucida Sans Unicode", "Lucida Grande", sans-serif', 'wooflow-email-customizer' ),
					'"Palatino Linotype", "Book Antiqua", Palatino, serif' => __( '"Palatino Linotype", "Book Antiqua", Palatino, serif', 'wooflow-email-customizer' ),
					'Georgia, serif' => __( 'Georgia, serif', 'wooflow-email-customizer' ),
				),
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woocommerce_table_style tr, .subscription-table tr.woo_label_tr, table#addresses .address p, p.additional_content_h6, p.first_span_text, .subscription-table th.subscription_price_th, .subscription-table td.subscription_price, table.subscription-table td.subscription_end_date, table.subscription-table th.subscription_end_date_th, p, ul li'   => array( 'font-family' ) )
					: array( '#body_content_inner .woocommerce_table_style *, #body_content_inner .subscription-table *, .first_span_text, .address p, .last_message, .additional_content_h6, #body_content_inner p, ul li'   => array( 'font-family' ) ,
				),
			),
			'table_content_font_size' => array(
				'title'    => esc_html__( 'Table Content Font Size', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['table_content_font_size']) ? $email_customizer_settings['table_content_font_size'] : $this->defaults['table_content_font_size'],
				'show'     => true,
				'class'     => 'colorset simple_class',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 10,
				'max'		=> 20,
				'unit'	=> 'px',
				'class'		=> 'table_content_font_size',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woocommerce_table_style tr, .subscription-table tr.woo_label_tr, table#addresses .address p, p.additional_content_h6, p.first_span_text, .subscription-table th.subscription_price_th, .subscription-table td.subscription_price, table.subscription-table td.subscription_end_date, table.subscription-table th.subscription_end_date_th, p, ul li'   => array( 'font-size' ) )
					: array( '#body_content_inner tr th, #body_content_inner tr td, p, #body_content_inner .subscription-table tr td a, #body_content_inner tr td span, #body_content_inner tr td small, p, ul li'   => array( 'font-size' ) ,
				),
			),
			'variation_product_font_size' => array(
				'title'    => esc_html__( 'Variation Font Size', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['variation_product_font_size']) ? stripslashes($email_customizer_settings['variation_product_font_size']) : $this->defaults['variation_product_font_size'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 10,
				'max'		=> 20,
				'unit'	=> 'px',
				'class'		=> 'variation_product_font_size',
				'style'  => 'css',
				'selectors'     => array(
					'span.variation_product' => array( 'font-size' ),
				),
			),
			'table_content_font_style' => array(
				'title'    => esc_html__( 'Font Style', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['table_content_font_style']) ? $email_customizer_settings['table_content_font_style'] : $this->defaults['table_content_font_style'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'100' => __( '100', 'wooflow-email-customizer' ),
					'200' => __( '200', 'wooflow-email-customizer' ),
					'300' => __( '300', 'wooflow-email-customizer' ),
					'400' => __( '400', 'wooflow-email-customizer' ),
					'500' => __( '500', 'wooflow-email-customizer' ),
					'600' => __( '600', 'wooflow-email-customizer' ),
					'700' => __( '700', 'wooflow-email-customizer' ),
					'bold' => __( 'Bold', 'wooflow-email-customizer' ),
				),
				'style'   => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woocommerce_table_style tr td span, .woocommerce_table_style tr.woo_label_tr th, .subscription-table tr.woo_label_tr th, .subscription-table tr.woo_label_tr, table#addresses .address p, a.user_id, p.additional_content_h6, p.first_span_text, .subscription-table th.subscription_price_th, .subscription-table td.subscription_price, table.subscription-table td.subscription_end_date, table.subscription-table th.subscription_end_date_th, p, ul li'   => array( 'font-weight' ) )
					: array('tr td, p'   => array( 'font-weight' ) ,
				),
			),
			'table_content_line_height' => array(
				'title'    => esc_html__( 'Content Line Height', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['table_content_line_height']) ? $email_customizer_settings['table_content_line_height'] : $this->defaults['table_content_line_height'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'min'       => 20,
				'max'       => 35,
				'unit'      => 'px',
				'class'     => 'table_content_line_height',
				'style'   => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.woocommerce_table_style tr, .subscription-table tr.woo_label_tr, table#addresses .address p, p.additional_content_h6, p.first_span_text, .subscription-table th.subscription_price_th, .subscription-table td.subscription_price, table.subscription-table td.subscription_end_date, table.subscription-table th.subscription_end_date_th, p, ul li'   => array( 'line-height' ) )
					: array('#body_content_inner .woocommerce_table_style tr th, #body_content_inner .subscription-table tr th, #body_content_inner .subscription-table tr td a, .first_span_text, .address p, .last_message, .additional_content_h6, p, ul li'   => array( 'line-height' ) ,
				),
			),
			'email_style_typography_email_address sub_menu_style' => array(
				'title'    => esc_html__( 'ADDRESS CONTENT', 'wooflow-email-customizer' ),
				'class'     => 'header_style_set',
			),
			'address_table_font_family' => array(
				'title'    => esc_html__( 'Font Family', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['address_table_font_family']) ? stripslashes($email_customizer_settings['address_table_font_family']) : $this->defaults['address_table_font_family'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'options'  => array(
					'"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif' => __( '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif', 'wooflow-email-customizer' ),
					'Arial, Helvetica, sans-serif' => __( 'Arial, Helvetica, sans-serif', 'wooflow-email-customizer' ),
					'"Arial Black", Gadget, sans-serif' => __( '"Arial Black", Gadget, sans-serif', 'wooflow-email-customizer' ),
					'"Courier New", Courier, monospace' => __( '"Courier New", Courier, monospace', 'wooflow-email-customizer' ),
					'Impact, Charcoal, sans-serif' => __( 'Impact, Charcoal, sans-serif', 'wooflow-email-customizer' ),
					'"Lucida Sans Unicode", "Lucida Grande", sans-serif' => __( '"Lucida Sans Unicode", "Lucida Grande", sans-serif', 'wooflow-email-customizer' ),
					'"Palatino Linotype", "Book Antiqua", Palatino, serif' => __( '"Palatino Linotype", "Book Antiqua", Palatino, serif', 'wooflow-email-customizer' ),
					'Georgia, serif' => __( 'Georgia, serif', 'wooflow-email-customizer' ),
				),
				'selectors'     => array(
					'table#addresses .address p, a.address_email' => array( 'font-family' ),
				),
			),
			'address_table_font_size' => array(
				'title'    => esc_html__( 'Table Content Font Size', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['address_table_font_size']) ? $email_customizer_settings['address_table_font_size'] : $this->defaults['address_table_font_size'],
				'show'     => true,
				'class'     => 'colorset simple_class',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 10,
				'max'		=> 20,
				'unit'	=> 'px',
				'class'		=> 'address_table_font_size',
				'style'  => 'css',
				'selectors'     => array(
					'table#addresses .address p, a.address_email' => array( 'font-size' ),
				),
			),
			'address_table_font_style' => array(
				'title'    => esc_html__( 'Font Style', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['address_table_font_style']) ? $email_customizer_settings['address_table_font_style'] : $this->defaults['address_table_font_style'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'100' => __( '100', 'wooflow-email-customizer' ),
					'200' => __( '200', 'wooflow-email-customizer' ),
					'300' => __( '300', 'wooflow-email-customizer' ),
					'400' => __( '400', 'wooflow-email-customizer' ),
					'500' => __( '500', 'wooflow-email-customizer' ),
					'600' => __( '600', 'wooflow-email-customizer' ),
					'700' => __( '700', 'wooflow-email-customizer' ),
					'bold' => __( 'Bold', 'wooflow-email-customizer' ),
				),
				'style'   => 'css',
				'selectors'     => array(
					'table#addresses .address p, a.address_email' => array( 'font-weight' ),
				),
			),
			'address_table_line_height' => array(
				'title'    => esc_html__( 'Content Line Height', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['address_table_line_height']) ? $email_customizer_settings['address_table_line_height'] : $this->defaults['address_table_line_height'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'min'       => 20,
				'max'       => 35,
				'unit'      => 'px',
				'class'     => 'address_table_line_height',
				'style'   => 'css',
				'selectors'     => array(
					'table#addresses .address p, a.address_email'   => array( 'line-height' ),
				),
			),
			'email_style_typography_email_footer sub_menu_style' => array(
				'title'    => esc_html__( 'FOOTER CONTENT', 'wooflow-email-customizer' ),
				'class'     => 'header_style_set',
			),
			'footer_content_font_family' => array(
				'title'    => esc_html__( 'Font Family', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['footer_content_font_family']) ? stripslashes($email_customizer_settings['footer_content_font_family']) : $this->defaults['footer_content_font_family'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset',
				'style'  => 'css',
				'options'  => array(
					'"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif' => __( '"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif', 'wooflow-email-customizer' ),
					'Arial, Helvetica, sans-serif' => __( 'Arial, Helvetica, sans-serif', 'wooflow-email-customizer' ),
					'"Arial Black", Gadget, sans-serif' => __( '"Arial Black", Gadget, sans-serif', 'wooflow-email-customizer' ),
					'"Courier New", Courier, monospace' => __( '"Courier New", Courier, monospace', 'wooflow-email-customizer' ),
					'Impact, Charcoal, sans-serif' => __( 'Impact, Charcoal, sans-serif', 'wooflow-email-customizer' ),
					'"Lucida Sans Unicode", "Lucida Grande", sans-serif' => __( '"Lucida Sans Unicode", "Lucida Grande", sans-serif', 'wooflow-email-customizer' ),
					'"Palatino Linotype", "Book Antiqua", Palatino, serif' => __( '"Palatino Linotype", "Book Antiqua", Palatino, serif', 'wooflow-email-customizer' ),
					'Georgia, serif' => __( 'Georgia, serif', 'wooflow-email-customizer' ),
				),
				'selectors'     => array(
					'#template_footer p' => array( 'font-family' ),
				),
			),
			'footer_content_font_size' => array(
				'title'    => esc_html__( 'Footer Font Size', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['footer_content_font_size']) ? $email_customizer_settings['footer_content_font_size'] : $this->defaults['footer_content_font_size'],
				'show'     => true,
				'class'     => 'colorset simple_class',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 10,
				'max'		=> 20,
				'unit'	=> 'px',
				'class'		=> 'footer_content_font_size',
				'style'  => 'css',
				'selectors'     => array(
					'#template_footer p' => array( 'font-size' ),
				),
			),
			'footer_content_font_style' => array(
				'title'    => esc_html__( 'Font Style', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['footer_content_font_style']) ? $email_customizer_settings['footer_content_font_style'] : $this->defaults['footer_content_font_style'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'100' => __( '100', 'wooflow-email-customizer' ),
					'200' => __( '200', 'wooflow-email-customizer' ),
					'300' => __( '300', 'wooflow-email-customizer' ),
					'400' => __( '400', 'wooflow-email-customizer' ),
					'500' => __( '500', 'wooflow-email-customizer' ),
					'600' => __( '600', 'wooflow-email-customizer' ),
					'700' => __( '700', 'wooflow-email-customizer' ),
					'bold' => __( 'Bold', 'wooflow-email-customizer' ),
				),
				'style'   => 'css',
				'selectors'     => array(
					'#template_footer p' => array( 'font-weight' ),
				),
			),
			'footer_content_line_height' => array(
				'title'    => esc_html__( 'Content Line Height', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['footer_content_line_height']) ? $email_customizer_settings['footer_content_line_height'] : $this->defaults['footer_content_line_height'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'min'       => 20,
				'max'       => 35,
				'unit'      => 'px',
				'class'     => 'footer_content_line_height',
				'style'   => 'css',
				'selectors'     => array(
					'#template_footer p'   => array( 'line-height' ),
				),
			),
			'Button_second_panel' => array(
				'id'	=> 'Button_second_panel',
				'title'       => esc_html__( 'Buttons', 'wooflow-email-customizer' ),
				'type'	=> 'section',
				'parent'=> 'Button_panel',
				'show'	=> true,
				'class' => 'sub_second_options_panel',
			),
			'fluid_button_size' => array(
				'title'    => esc_html__( 'Button Size', 'wooflow-email-customizer' ),
				'type'     => 'radio_button_design',
				'default'  => isset($email_customizer_settings['fluid_button_size']) ? $email_customizer_settings['fluid_button_size'] : $this->defaults['fluid_button_size'],
				'show'     => true,
				'choices' => array(
					15 => __( 'Normal', 'wooflow-email-customizer' ),
					20 => __( 'Large', 'wooflow-email-customizer'  )
				),
				'option_name' => 'email_customizer_settings_option',
				'option_type' => 'array',
			),
			'fluid_button_background_color' => array(
				'title'    => esc_html__( 'Button Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'default'  => !empty($email_customizer_settings['fluid_button_background_color']) ? $email_customizer_settings['fluid_button_background_color'] : $this->defaults['fluid_button_background_color'],
				'show'     => true,
				'option_name' => 'email_customizer_settings_option',
				'option_type' => 'array',
				'selectors'     => array(
					'p.customer_account_btn, .invoice_btn' => array( 'background-color' ),
				),
			),	
			'fluid_button_font_color' => array(
				'title'    => esc_html__( 'Button Font Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'default'  => !empty($email_customizer_settings['fluid_button_font_color']) ? $email_customizer_settings['fluid_button_font_color'] : $this->defaults['fluid_button_font_color'],
				'show'     => true,
				'option_name' => 'email_customizer_settings_option',
				'option_type' => 'array',
				'style'  => 'css',
				'selectors'     => array(
					'button.invoice_btn a, .customer_account_btn a' => array( 'color' ),
				),
			),
			'fluid_button_border' => array(
				'title'    => esc_html__( 'Button Border Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['fluid_button_border']) ? stripslashes($email_customizer_settings['fluid_button_border']) : $this->defaults['fluid_button_border'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'option_key' => 'fluid_button_border',
				'min'		=> 1,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'fluid_button_border',
				'style'  => 'css',
				'selectors'     => array(
					'p.customer_account_btn' => array( 'border-width' ),
				),
			),
			'fluid_button_radius' => array(
				'title'    => esc_html__( 'Button Radius', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => !empty($email_customizer_settings['fluid_button_radius']) ? $email_customizer_settings['fluid_button_radius'] : $this->defaults['fluid_button_radius'],
				'min'	   => 1,	
				'max'	   => 20,
				'show'     => true,
				'option_name' => 'email_customizer_settings_option',
				'class'		=> 'border_bottom_none',
				'option_type' => 'array',
			),
			'header4' => array(
				'id'     => 'Container_panel',
				'title'       => esc_html__( 'Email Container', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'Container_panel',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'Container_sub_panel' => array(
				'id'	=> 'Container_sub_panel',
				'type'	=> 'sub-panel',
				'parent'=> 'Container_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'Container_second_panel' => array(
				'id'	=> 'Container_second_panel',
				'title'       => esc_html__( 'Email Container', 'wooflow-email-customizer' ),
				'type'	=> 'section',
				'parent'=> 'Container_sub_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'woocommerce_email_body_background_color' => array(
				'title'    => esc_html__( 'Container Background Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'default'  => get_option( 'woocommerce_email_body_background_color' ),
				'show'     => true,
				'option_name' => 'woocommerce_email_body_background_color',
				'option_type' => 'key',
				'class' => 'container_background_color',
				'style'  => 'css',
				'selectors'     => array(
					'#body_content_inner' => array( 'background-color' ),
				),
			),	
			'container_padding_top' => array(
				'title'    => esc_html__( 'Padding Top', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['container_padding_top']) ? stripslashes($email_customizer_settings['container_padding_top']) : $this->defaults['container_padding_top'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 50,
				'unit'	=> 'px',
				'class'		=> 'Container_padding_top',
				'style'  => 'css',
				'selectors'     => array(
					'#body_content_inner' => array( 'padding-top' ),
				),
			),
			'container_padding_bottom' => array(
				'title'    => esc_html__( 'Padding Bottom', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['container_padding_bottom']) ? stripslashes($email_customizer_settings['container_padding_bottom']) : $this->defaults['container_padding_bottom'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 50,
				'unit'	=> 'px',
				'class'		=> 'Container_padding_bottom',
				'style'  => 'css',
				'selectors'     => array(
					'#body_content_inner' => array( 'padding-bottom' ),
				),
			),
			'container_padding_left_right' => array(
				'title'    => esc_html__( 'Padding Left/Right', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['container_padding_left_right']) ? stripslashes($email_customizer_settings['container_padding_left_right']) : $this->defaults['container_padding_left_right'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 50,
				'unit'	=> 'px',
				'class'		=> 'container_padding_left_right',
				'style'  => 'css',
				'selectors'     => array(
					'#body_content_inner' => array( 'padding-left' ),
					'#body_content_inner' => array( 'padding-right' ),
				),
			),
			'container_width' => array(
				'title'    => esc_html__( 'Container Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['container_width']) ? stripslashes($email_customizer_settings['container_width']) : $this->defaults['container_width'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 600,
				'max'		=> 800,
				'unit'	=> 'px',
				'class'		=> 'container_width',
				'style'  => 'css',
				'selectors'     => array(
					'#template_container' => array( 'width' ),
				),
			),
			'container_border' => array(
				'title'    => esc_html__( 'Border Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['container_border']) ? stripslashes($email_customizer_settings['container_border']) : $this->defaults['container_border'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 1,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'container_border zorem_template_none',
				'style'  => 'css',
				'selectors'     => array(
					'#template_container' => array( 'border-width' ),
				),
			),
			'container_border_radius' => array(
				'title'    => esc_html__( 'Border Radius', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['container_border_radius']) ? stripslashes($email_customizer_settings['container_border_radius']) : $this->defaults['container_border_radius'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 1,
				'max'		=> 20,
				'unit'	=> 'px',
				'class'		=> 'container_border_radius border_bottom_none',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('table#template_body'   => array( 'border-radius' ) )
					: array('table#template_container'   => array( 'border-radius' ) ,
				),
			),
			'header5' => array(
				'id'     => 'header_panel',
				'title'       => esc_html__( 'Email Header', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'header_panel',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'header_sub_panel' => array(
				'id'	=> 'header_sub_panel',
				'type'	=> 'sub-panel',
				'parent'=> 'header_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'header_second_panel' => array(
				'id'	=> 'header_second_panel',
				'title'       => esc_html__( 'Email Header', 'wooflow-email-customizer' ),
				'type'	=> 'section',
				'parent'=> 'header_sub_panel',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'woocommerce_email_header_image' => array(	
				'type'		=> 'media',
				'title'    => esc_html__( 'Header Logo', 'wooflow-email-customizer' ),			
				'show'		=> true,
				'default'   =>  get_option('woocommerce_email_header_image'),
				'option_name'=> 'woocommerce_email_header_image',
				'option_type'=> 'key',					
				// 'class'     => 'border-top-verification',
				'style'  => 'css',
				'selectors'    => array(
					'#template_header_image p img',
				),
			),
			'logo_width' => array(
				'title'    => esc_html__( 'Logo Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'parent'	=> 'email_heading',
				'default'  => isset($email_customizer_settings['logo_width']) ? $email_customizer_settings['logo_width'] : $this->defaults['logo_width'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 500,
				'unit'	=> 'px',
				'show'     => true,
				'style'  => 'css',
				'selectors'     => array(
					'#wrapper template_header_image img, #wrapper #template_container img' => array( 'width' ),
				),
			),
			'header_width' => array(
				'title'    => esc_html__( 'Header Width', 'wooflow-email-customizer' ),
				'type'     => 'radio_button_design',
				'default'  => isset($email_customizer_settings['header_width']) ? $email_customizer_settings['header_width'] : $this->defaults['header_width'],
				'show'     => true,
				'choices' => array(
					1 => __( 'Full Width', 'wooflow-email-customizer' ),
					0 => __( 'Normal', 'wooflow-email-customizer'  )
				),
				'option_name' => 'email_customizer_settings_option',
				'option_type' => 'array',
				'class'   => 'header_show_zorem_template',
			),
			'logo_position' => array(
				'title'    => esc_html__( 'Logo Position', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['logo_position']) ? $email_customizer_settings['logo_position'] : $this->defaults['logo_position'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'class'     => 'logo_position',
				'options'  => array(
					'outside' => __( 'Outside Body Container', 'wooflow-email-customizer' ),
					'inside' => __( 'Inside Body Container', 'wooflow-email-customizer' ),
				),
			),
			'logo_alignment' => array(
				'title'    => esc_html__( 'Logo Alignment', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['logo_alignment']) ? $email_customizer_settings['logo_alignment'] : $this->defaults['logo_alignment'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'left' => __( 'Left', 'wooflow-email-customizer' ),
					'right' => __( 'Right', 'wooflow-email-customizer' ),
					'center' => __( 'Center', 'wooflow-email-customizer' ),
				),
			),
			'heading_text_alignment' => array(
				'title'    => esc_html__( 'Heading Alignment', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['heading_text_alignment']) ? $email_customizer_settings['heading_text_alignment'] : $this->defaults['heading_text_alignment'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'heading_text_alignment',
				'show'     => true,
				'options'  => array(
					'left' => __( 'Left', 'wooflow-email-customizer' ),
					'right' => __( 'Right', 'wooflow-email-customizer' ),
					'center' => __( 'Center', 'wooflow-email-customizer' ),
				),
				'style'  => 'css',
				'selectors'     => array(
					'body h1' => array( 'text-align' ),
				),
			),
			'woocommerce_email_base_color' => array(
				'title'    => esc_html__( 'Header Background Color', 'wooflow-email-customizer' ),
				'default'  => get_option( 'woocommerce_email_base_color' ),
				'type'     => 'color',
				'parent'	=> 'email_heading',
				'show'     => true,
				'option_name'=> 'woocommerce_email_base_color',
				'option_type'=> 'key',
				'class'     => 'colorset header_show_woocommerce_template',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('.header_container'   => array( 'background-color' ) )
					: array('td#header_wrapper, .header_container'   => array( 'background-color' ) ,
				),
			),
			'heading_padding_top' => array(
				'title'    => esc_html__( 'Padding Top', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'parent'	=> 'email_heading',
				'default'  => isset($email_customizer_settings['heading_padding_top']) ? $email_customizer_settings['heading_padding_top'] : $this->defaults['heading_padding_top'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 50,
				'unit'	=> 'px',
				'show'     => true,
				'style'  => 'css',
				'class'     => 'heading_padding_top',
				'selectors'     => array(
					'#header_wrapper' => array( 'padding-top' ),
				),
			),
			'heading_padding_bottom' => array(
				'title'    => esc_html__( 'Padding Bottom', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'parent'	=> 'email_heading',
				'default'  => isset($email_customizer_settings['heading_padding_bottom']) ? $email_customizer_settings['heading_padding_bottom'] : $this->defaults['heading_padding_bottom'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 50,
				'unit'	=> 'px',
				'show'     => true,
				'style'  => 'css',
				'class'     => 'heading_padding_bottom',
				'selectors'     => array(
					'#header_wrapper' => array( 'padding-bottm' ),
				),
			),
			'heading_padding_left_right' => array(
				'title'    => esc_html__( 'Padding left/right', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'parent'	=> 'email_heading',
				'default'  => isset($email_customizer_settings['heading_padding_left_right']) ? $email_customizer_settings['heading_padding_left_right'] : $this->defaults['heading_padding_left_right'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 150,
				'unit'	=> 'px',
				'class' => 'border_bottom_none heading_padding_left_right',
				'show'     => true,
				'style'  => 'css',
				'selectors'     => array(
					'#header_wrapper' => array( 'padding-left' ),
					'#header_wrapper' => array( 'padding-right' ),
				),
			),
			'order_second_panel' => array(
				'id'	=> 'order_second_panel',
				'title'       => esc_html__( 'Order Details', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'template_setting_second',
				'show'     => true,	
				'class' => 'sub_second_options_panel',
			),
			'show_product_image' => array(
				'title'    => esc_html__( 'Show Product Image', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['show_product_image']) ? $email_customizer_settings['show_product_image'] : $this->defaults['show_product_image'],
				'type' => 'select',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class' => 'show_product_image',
				'show'     => true,
				'options'  => array(
					'0' => __( 'No', 'wooflow-email-customizer' ),
					'1' => __( 'Yes', 'wooflow-email-customizer' ),
				),
			),
			'order_summary_background_color' => array(
				'title'    => esc_html__( 'Order Table Background Color', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['order_summary_background_color']) ? stripslashes($email_customizer_settings['order_summary_background_color']) : $this->defaults['order_summary_background_color'],
				'type'     => 'color',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'default_color' => '#ffffff',
				'class'     => 'colorset order_summary_background_color',
				'style'  => 'css',
				'selectors'     => array(
					'#body_content_inner table.woocommerce_table_style, table.woocommerce_table_style tbody .order_item, table.subscription_table'   => array( 'background-color' ),
					
				),
			),
			'table_padding_top' => array(
				'title'    => esc_html__( 'Padding Top', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['table_padding_top']) ? stripslashes($email_customizer_settings['table_padding_top']) : $this->defaults['table_padding_top'],
				'type'     => 'range',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 25,
				'unit'	=> 'px',
				'class'		=> 'table_padding_top',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('table.woocommerce_table_style'   => array( 'padding-top' ) )
					: array('table.woocommerce_table_style'   => array( 'margin-top' ) ,
				),
			),
			'table_padding_bottom' => array(
				'title'    => esc_html__( 'Padding Bottom', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['table_padding_bottom']) ? stripslashes($email_customizer_settings['table_padding_bottom']) : $this->defaults['table_padding_bottom'],
				'type'     => 'range',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 25,
				'unit'	=> 'px',
				'class'		=> 'table_padding_bottom',
				'style'  => 'css',
				'selectors_template' => 'trackship_SaaS' == $email_template ? array('table.woocommerce_table_style'   => array( 'padding-bottom' ) )
					: array('table.woocommerce_table_style'   => array( 'margin-bottom' ) ,
				),
			),
			// 'table_left_right_padding' => array(
			// 	'title'    => esc_html__( 'Left / Right Padding', 'wooflow-email-customizer' ),
			// 	'default'  => isset($email_customizer_settings['table_left_right_padding']) ? stripslashes($email_customizer_settings['table_left_right_padding']) : $this->defaults['table_left_right_padding'],
			// 	'type'     => 'range',
			// 	'show'     => 'trackship_SaaS' == $email_template ? false : true,
			// 	'option_name'=> 'email_customizer_settings_option',
			// 	'option_type'=> 'array',
			// 	'min'		=> 0,
			// 	'max'		=> 15,
			// 	'unit'	=> 'px',
			// 	'class'		=> Wooflow_Email_Customizer()->is_subscription_active() ? 'table_left_right_padding' : ' table_left_right_padding border_bottom_none ',
			// 	'style'  => 'css',
			// 	'selectors'     => array(
			// 		'#body_content_inner table.td th, th.td.tlabel-subtotal, td.td.tvalue-subtotal, td.td.tvalue-total, th.td.tlabel-shipping, th.td.tlabel-paymentmethod,td.td.tvalue-shipping, td.td.tvalue-paymentmethod, th.td.tlabel-total, td.td.tvalue-vat, td.td.tlabel-vat, td.td.note-add, td.td.note-two, th.td.copify-td' => array( 'padding-left','padding-right' ),
			// 		'#body_content_inner table.td td, td.td.note-add, td.td.note-two' => array( 'padding-left','padding-right' ),
			// 	),
			// ),
			'order_details_border' => array(
				'title'    => esc_html__( 'Border Width', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['order_details_border']) ? stripslashes($email_customizer_settings['order_details_border']) : $this->defaults['order_details_border'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 1,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'order_details_border',
				'style'  => 'css',
				'selectors'     => array(
					'table.woocommerce_table_style, th.woo_product_th, th.woo_price_th' => array( 'border-width' ),
					'table.woocommerce_table_style td.woo_image_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style td.woo_price_id, table.woocommerce_table_style th.woo_label_th, table.woocommerce_table_style td.woo_value_th, th.woo_note_th, td.woo_note_value_th' => array( 'border-top-width' ),
					'table.woocommerce_table_style th.woo_product_th, table.woocommerce_table_style th.woo_qty_th, table.woocommerce_table_style td.woo_image_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style td.woo_qty_id, table.woocommerce_table_style th.woo_label_th, th.woo_note_th' => array( 'border-right-width' ),
				),
			),
			'order_details_border_radius' => array(
				'title'    => esc_html__( 'Border Radius', 'wooflow-email-customizer' ),
				'type'     => 'range',
				'default'  => isset($email_customizer_settings['order_details_border_radius']) ? stripslashes($email_customizer_settings['order_details_border_radius']) : $this->defaults['order_details_border_radius'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'order_details_border_radius border_bottom_none zorem_template_none',
				'style'  => 'css',
				'selectors'     => array(
					'table.woocommerce_table_style' => array( 'border-radius' ),
				),
			),
			'header6' => array(
				'id'     => 'email_footer',
				'title'       => esc_html__( 'Email Footer', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'email_footer',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'email_footer_panel' => array(
				'id'	=> 'email_footer_panel',
				'type'	=> 'sub-panel',
				'parent'=> 'email_footer',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'footer_second_panel' => array(
				'id'	=> 'footer_second_panel',
				'title'       => esc_html__( 'Email Footer', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'email_footer_panel',
				'show'     => true,	
				'class' => 'sub_options_panel',
			),
			'email_footer_text' => array(
				'title'    => esc_html__( 'Absolute Footer Text', 'wooflow-email-customizer' ),
				'type'     => 'text',
				'default'  => isset($email_customizer_settings['email_footer_text']) ? $email_customizer_settings['email_footer_text'] : $this->defaults['email_footer_text'],
				'placeholder' => '',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'style'  => 'css',
				'class'		=> 'input_width_height footer_text_edit',
				'selectors'     => array(
					'td#credit p'
				),
			),
			'footer_layout' => array(
				'title'    => esc_html__( 'Footer Alignment ', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['footer_layout']) ? $email_customizer_settings['footer_layout'] : $this->defaults['footer_layout'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'		=> 'hide_show footer_layout',
				'options'  => array(
					'center' => __( 'Center', 'wooflow-email-customizer' ),
					'left' => __( 'Left', 'wooflow-email-customizer' ),
					'right' => __( 'Right', 'wooflow-email-customizer' ),
				),
				'hide'		=> true,
				'style'  => 'css',
				'selectors'     => array(
					'#template_footer #credit, table#template_footer p'
				),
			),
			'footer_position' => array(
				'title'    => esc_html__( 'Footer Placement', 'wooflow-email-customizer' ),
				'type'     => 'select',
				'default'  => isset($email_customizer_settings['footer_position']) ? $email_customizer_settings['footer_position'] : $this->defaults['footer_position'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'options'  => array(
					'Inside' => __( 'Inside Footer', 'wooflow-email-customizer' ),
					'Outside' => __( 'Outside Footer', 'wooflow-email-customizer' ),
				),
				'class' => 'show_footer_position',
			),
			'footer_width' => array(
				'title'    => esc_html__( 'Footer Width', 'wooflow-email-customizer' ),
				'type'     => 'radio_button_design',
				'default'  => isset($email_customizer_settings['footer_width']) ? $email_customizer_settings['footer_width'] : $this->defaults['footer_width'],
				'show'     => 'zorem' == $email_template ? false : true,
				'choices' => array(
					1 => __( 'Full Width', 'wooflow-email-customizer' ),
					0 => __( 'Normal', 'wooflow-email-customizer'  )
				),
				'option_name' => 'email_customizer_settings_option',
				'option_type' => 'array',
				'class'   => 'header_show_zorem_template',
			),
			'footer_background_color' => array(
				'title'    => esc_html__( 'Background Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'default'  => isset($email_customizer_settings['footer_background_color']) ? $email_customizer_settings['footer_background_color'] : $this->defaults['footer_background_color'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset simple_class footer_background_color Footer_position_outside_hide',
				'style'   => 'css',
				'selectors'     => array(
					'#template_footer_container' => array( 'background-color' ),
					'#template_footer' => array( 'background-color' ),
					'.aec_footer_layout' => array( 'background-color' ),
				),
			),
			'footer_icon_background_color' => array(
				'title'    => esc_html__( 'Icon Background Color', 'wooflow-email-customizer' ),
				'type'     => 'color',
				'default'  => isset($email_customizer_settings['footer_icon_background_color']) ? $email_customizer_settings['footer_icon_background_color'] : $this->defaults['footer_icon_background_color'],
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'class'     => 'colorset simple_class',
				'style'   => 'css',
				'selectors'     => array(
					'.social-link-url img' => array( 'background-color' ),
				),
			),
			'footer_border_bottom' => array(
				'title'    => esc_html__( 'Footer Divider Type', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['footer_border_bottom']) ? stripslashes($email_customizer_settings['footer_border_bottom']) : $this->defaults['footer_border_bottom'],
				'type'     => 'select',
				'parent'	=> 'email_heading',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'style'  => 'css',
				'class'		=> 'footer_border_bottom Footer_position_outside_hide',
				'selectors'     => array(
					'table#template_footer'   => array( 'border-top-style' ),
				),
				'options'  => array(
					'solid' => __( 'Solid', 'wooflow-email-customizer' ),
					'dotted' => __( 'Dotted', 'wooflow-email-customizer' ),
					'double' => __( 'Double', 'wooflow-email-customizer' ),
					'groove' => __( 'Groove', 'wooflow-email-customizer' ),
					'dashed' => __( 'Dashed', 'wooflow-email-customizer' ),
					'ridge' => __( 'Ridge', 'wooflow-email-customizer' ),
				),
			),
			'footer_border_bottom_color' => array(
				'title'    => esc_html__( 'Footer Divider Color', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['footer_border_bottom_color']) ? stripslashes($email_customizer_settings['footer_border_bottom_color']) : $this->defaults['footer_border_bottom_color'],
				'type'     => 'color',
				'parent'	=> 'email_heading',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'footer_border_bottom_color Footer_position_outside_hide',
				'style'  => 'css',
				'selectors'     => array(
					'table#template_footer'   => array( 'border-color' ),
				),
			),
			'footer_border_bottom_width' => array(
				'title'    => esc_html__( 'Footer Divider Width', 'wooflow-email-customizer' ),
				'default'  => isset($email_customizer_settings['footer_border_bottom_width']) ? stripslashes($email_customizer_settings['footer_border_bottom_width']) : $this->defaults['footer_border_bottom_width'],
				'type'     => 'range',
				'parent'	=> 'email_heading',
				'show'     => true,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'min'		=> 0,
				'max'		=> 5,
				'unit'	=> 'px',
				'class'		=> 'footer_border_bottom_width Footer_position_outside_hide',
				'style'  => 'css',
				'selectors'     => array(
					'table#template_footer'   => array( 'border-top-width' ),
				),
			),
			'link_show' => array(
				'label'    => esc_html__( 'Display Footer Links Menu ', 'wooflow-email-customizer' ),
				'type'     => 'checkbox',
				'default'  => isset($email_customizer_settings['link_show']) ? $email_customizer_settings['link_show'] : $this->defaults['link_show'],
				'show'     => false,
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'transport' => 'refresh',
				'class'     => 'link_show',
			),
			'footer_text_add' => array(
				'type'     => 'footer_link_text',
				'default'  => isset($email_customizer_settings['footer_text_add']) ? $email_customizer_settings['footer_text_add'] : $this->defaults['footer_text_add'],
				'placeholder' => 'text',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'hide'		=> 'trackship_SaaS' == $email_template ? false : true,
				'class'		=> 'footer_link_text hide_show',
			),
		
			'footer_social_media_options sub_menu_style' => array(
				'title'    => esc_html__( 'Social Media', 'wooflow-email-customizer' ),
				'class'		=> 'header_style_set',
			),
	
			'facebook_link' => array(
				'title'    => esc_html__( 'Facebook Link', 'wooflow-email-customizer' ),
				'type'     => 'text',
				'default'  => isset($email_customizer_settings['facebook_link']) ? $email_customizer_settings['facebook_link'] : $this->defaults['facebook_link'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
			),
			'twitter_link' => array(
				'title'    => esc_html__( 'Twitter Link', 'wooflow-email-customizer' ),
				'type'     => 'text',
				'default'  => isset($email_customizer_settings['twitter_link']) ? $email_customizer_settings['twitter_link'] : $this->defaults['twitter_link'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
			),
			'linkedin_link' => array(
				'title'    => esc_html__( 'LinkedIn Link', 'wooflow-email-customizer' ),
				'type'     => 'text',
				'default'  => isset($email_customizer_settings['linkedin_link']) ? $email_customizer_settings['linkedin_link'] : $this->defaults['linkedin_link'],
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
			),
			'custom_style_section' => array(
				'id'	=> 'custom_style_section',
				'title'       => esc_html__( 'Custom CSS', 'wooflow-email-customizer' ),
				'type'	=> 'section',
				'parent'=> 'custom_style',
				'show'	=> true,
				'class' => 'sub_second_options_panel',
			),
			'custom_style_textarea' => array(
				'title'    => esc_html__( 'Custom CSS', 'wooflow-email-customizer' ),
				'type'     => 'textarea',
				'default'  => isset($email_customizer_settings['custom_style_textarea']) ? $email_customizer_settings['custom_style_textarea'] : $this->defaults['custom_style_textarea'],
				'show'     => true,
				'option_name' => 'email_customizer_settings_option',
				'option_type' => 'array',
				'option_key'=> 'custom_style_textarea',
				'class' => 'border_bottom_none',
				'selectors'     => array(
					'style#wooflow_email_design_custom_css',
				),
			),	
			'header7' => array(
				'id'     => 'import_export_btn',
				'title'       => esc_html__( 'Import Export', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'import_export_btn',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'import_export_options' => array(
				'id'	=> 'import_export_options',
				'type'	=> 'sub-panel',
				'parent'=> 'import_export_btn',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'import_export_section' => array(
				'id'     => 'import_export_section',
				'title'       => esc_html__( 'Import Export', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'import_export_options',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'import_export_option' => array(
				'type'     => 'inport_export_buttons',
				'default'  => isset($email_customizer_settings['import_export_option']) ? $email_customizer_settings['import_export_option'] : '',
				'option_name'=> 'email_customizer_settings_option',
				'option_type'=> 'array',
				'show'     => true,
				'class' => 'border_bottom_none',
			),
			'header8' => array(
				'id'     => 'send_test_email',
				'title'       => esc_html__( 'Send Test Email', 'wooflow-email-customizer' ),
				'type'     => 'sub-panel-heading',
				'parent'	=> 'send_test_email',
				'show'     => true,
				'class' => 'sub_options_panel',
			),
			'send_test_email_options' => array(
				'id'	=> 'send_test_email_options',
				'type'	=> 'sub-panel',
				'parent'=> 'send_test_email',
				'show'	=> true,
				'class' => 'sub_options_panel',
			),
			'send_test_email_section' => array(
				'id'     => 'send_test_email_section',
				'title'       => esc_html__( 'Send Test Email', 'wooflow-email-customizer' ),
				'type'     => 'section',
				'parent'	=> 'send_test_email_options',
				'show'     => true,
				'class' => ' sub_options_panel',
			),
			'send_to_email' => array(
				'title'    => esc_html__( 'Enter Email Address (Comma Separated)', 'wooflow-email-customizer' ),
				'type'     => 'email_type_set',
				'default'  => get_option('admin_email'),
				'show'     => true,
				'class' => 'border_bottom_none',
			),
		);
	
		$settings = apply_filters( 'wooflow_customizer_setting_options' , $settings );
		return $settings; 
	}
}
